# Generated by Django 4.1.5 on 2023-01-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_first_name', models.CharField(max_length=200)),
                ('patient_last_name', models.CharField(max_length=200)),
                ('patient_birthdate', models.DateField()),
            ],
        ),
    ]
